In [12]:
import numpy as np
#normal list
my_array_list = [20,30,40,50,60,70]

#numpy array
numpy_array = np.array([20,30,40,50,60,70])

print(my_array_list)
print(numpy_array)


[20, 30, 40, 50, 60, 70]
[20 30 40 50 60 70]


In [13]:
my_list = [10,20,30,40,50]
my_array = np.array([10,20,30,40,50])
print(my_list*2)
print(my_array*2)

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]
[ 20  40  60  80 100]


In [21]:
salaries = np.array([75000,80000,90000,60000])
inc_sal = salaries*1.10
print(inc_sal) #. in output is indicating that it's float

[82500. 88000. 99000. 66000.]


In [19]:
my_array = np.array([10, 20, 30, 40, 50])
print(my_array + 5)
print(my_array ** 2)
print(my_array - 3)
print(my_array / 2) #division always returns float in Python. Even 10 / 2 = 5.0 not 5
print(my_array // 2)  # [5 10 15 20 25] ← no dots! // means floor division — whole numbers only. Same as PHP's intdiv()

[15 25 35 45 55]
[ 100  400  900 1600 2500]
[ 7 17 27 37 47]
[ 5. 10. 15. 20. 25.]
[ 5 10 15 20 25]


In [20]:
#numpy array concept : One operation → applies to every number in the array automatically This is called vectorisation.

In [28]:
#math functions : max, min, sum, mean
my_array = np.array([10, 20, 30, 40, 50])
print("Sum : ", np.sum(my_array))
print("Average : ", np.mean(my_array))
print("Max : ", np.max(my_array))
print("Min : ", np.min(my_array))

Sum :  150
Average :  30.0
Max :  50
Min :  10


In [33]:
# Filtering data from numpy array just like we do in sql
scores = np.array([20,40,60,80,90, 67, 56, 87, 99, 88])
# score greater than 60
# like in sql: select * from scores where score > 60
passed = scores[scores > 60] #means : From scores, give me only the ones where score is greater than 60
print("passed : ",passed)

passed :  [80 90 67 87 99 88]


In [34]:
scores = np.array([85, 42, 90, 33, 76, 55, 89, 45])

# Greater than
print(scores[scores > 60])

# Less than
print(scores[scores < 50])

# Equal to
print(scores[scores == 85])

# Not equal to
print(scores[scores != 85])

[85 90 76 89]
[42 33 45]
[85]
[42 90 33 76 55 89 45]


In [35]:
#Multiple conditions — like SQL AND / OR
scores = np.array([85, 42, 90, 33, 76, 55, 89, 45])

# AND condition (both must be true)
print(scores[(scores > 60) & (scores < 90)])

# OR condition (either can be true)
print(scores[(scores < 40) | (scores > 85)])

[85 76 89]
[90 33 89]


In [37]:
scores = np.array([85, 42, 90, 33, 76, 55, 89, 45])

# 1. Print scores that are exactly 90
print(scores[(scores == 90)])
# 2. Print scores that are NOT 42
print(scores[scores != 42])
# 3. Print scores greater than 50 AND less than 80
print(scores[(scores > 50) & (scores < 80)])

[90]
[85 90 33 76 55 89 45]
[76 55]


In [39]:
# 2D arrays
marks = np.array([
    [20,30,40],
    [40,50,60],
    [60,70,90]
])
print(marks)
print("shape : ", marks.shape)
#.shape property lives inside array that's why marks.shape and not shape.marks

[[20 30 40]
 [40 50 60]
 [60 70 90]]
shape :  (3, 3)


In [40]:
# 4 students, 2 subjects each
marks = np.array([
    [85, 90],
    [55, 42],
    [90, 88],
    [70, 65]
])

print(marks)
print("Shape:", marks.shape)    # should print (4, 2)
print("Rows:", marks.shape[0])  # 4 students
print("Cols:", marks.shape[1])  # 2 subjects

[[85 90]
 [55 42]
 [90 88]
 [70 65]]
Shape: (4, 2)
Rows: 4
Cols: 2


In [41]:
one_d = np.array([10, 20, 30])
two_d = np.array([[10, 20, 30]])

print("1D:", one_d)
print("2D:", two_d)
print("1D shape:", one_d.shape)
print("2D shape:", two_d.shape)


1D: [10 20 30]
2D: [[10 20 30]]
1D shape: (3,)
2D shape: (1, 3)


In [42]:
#Simple rule to remember:
#Always check .shape whenever you load new data — before doing anything else.
#It's like checking count($array) in PHP before processing it — just a sanity check habit

In [56]:
# 3 students, 3 subjects (Math, English, Science)
marks = np.array([
    [85, 90, 78],   # Student 1
    [55, 42, 66],   # Student 2
    [90, 88, 95],   # Student 3
])
print(marks)
# Get entire first row (Student 1's all marks)
print(marks[0])
# Get entire second row (Student 2's all marks)
print(marks[1])
# Get one specific value - row 0, column 1
print(marks[0][1])
# Get entire first column (everyone's Math marks)
print(marks[:,0]) #": means Give me ALL rows, but only column 0"
# Get entire second column (everyone's English marks)
print(marks[:, 1])
print("------------------------")
# 1. Print Student 3's all marks
print(marks[2, :])
# 2. Print everyone's Science marks (column 2)
print(marks[:, 2])
# 3. Print Student 2's English mark (row 1, column 1)
print(marks[1][1])

[[85 90 78]
 [55 42 66]
 [90 88 95]]
[85 90 78]
[55 42 66]
90
[85 55 90]
[90 42 88]
------------------------
[90 88 95]
[78 66 95]
42
